
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  purge_keep_days: 14
  purge_interval: 2
  db_url: !secret mariadb_connection_url

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

#lovelace: 
#  mode: yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
counter: !include counters.yaml
sensor: !include sensors.yaml
homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml
  javascript_version: latest

pi_hole:
  - host: '192.168.1.200'

# Router
asuswrt:
  host: 192.168.1.5
  username: admin
  password: !secret router
  protocol: ssh

# Presence detection via Router
device_tracker:
  - platform: asuswrt
    consider_home: 30
    interval_seconds: 15
    new_device_defaults:
      track_new_devices: false


# Xiaomi gateway
# https://www.home-assistant.io/integrations/xiaomi_aqara/
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway

# Yeelights
# https://www.home-assistant.io/integrations/yeelight/
yeelight: !include yeelight.yaml

# Android IP Webcam
# https://www.home-assistant.io/integrations/android_ip_webcam/
android_ip_webcam:
  - host: 192.168.1.209
    port: 8080
    username: Homecam
    password: !secret android_ip_webcam
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

# Plant Watering
# Using GPIO to turn on MOSFET(thus a pump) for x sec https://www.home-assistant.io/integrations/rpi_gpio/
switch:
  - platform: rpi_gpio
    ports: #Refers to GPIO #, not pin#. Ex: 17 below is pin11.
      17: mosfet_gate
        
# Weather
weather:
  - platform: openweathermap
    name: OpenWeatherMap
    api_key: 3dc8ede494fbe8aa28d86a131f56cc2b